export const defaultAgendaEvents = [
  {
    id: "e-001",
    title: "Reunion con cliente",
    weekday: 0,
    start: "09:00",
    end: "10:30",
    category: "general",
    tone: "accent",
  },
  {
    id: "e-002",
    title: "Revision de inventario",
    weekday: 0,
    start: "11:00",
    end: "11:45",
    category: "general",
    tone: "blue",
  },
  {
    id: "e-003",
    title: "Visita a obra",
    weekday: 1,
    start: "08:00",
    end: "10:00",
    category: "proyecto",
    tone: "accent",
  },
  {
    id: "e-004",
    title: "Cotizaciones pendientes",
    weekday: 2,
    start: "14:00",
    end: "15:30",
    category: "cotizacion",
    tone: "blue",
  },
  {
    id: "e-005",
    title: "Mantenimiento de herramientas",
    weekday: 3,
    start: "16:00",
    end: "17:00",
    category: "general",
    tone: "gray",
  },
  {
    id: "e-006",
    title: "Entrega de materiales",
    weekday: 4,
    start: "10:30",
    end: "11:30",
    category: "proyecto",
    tone: "accent",
  },
];
